# Generated by Django 4.2.1 on 2023-05-18 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0001_initial'),
        ('transmission', '0001_initial'),
        ('color', '0001_initial'),
        ('model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('max_speed', models.IntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('engine', models.FloatField()),
                ('year', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.body')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.color')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transmission.transmission')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
